#!/usr/bin/env python3
"""
Robust AI Components Data Seeding Script
Ensures AI Suggestor and AI Generator have all necessary configuration data
Never crashes - comprehensive error handling
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import app, db
from models import Template

# AI Suggestor Configuration
# AI supports ANY template type requested by users (truly unlimited)
# Database categories are just for browsing existing templates
# These are just examples for reference
EXAMPLE_TEMPLATE_TYPES = [
    "Project Charter",
    "Project Plan",
    "Risk Management",
    "Quality Management",
    "Resource Management",
    "Communication Plan",
    "Stakeholder Management",
    "Budget Management",
    "Schedule Management",
    "Scope Management",
    "Procurement Management",
    "Change Management",
    "Issue Management",
    "Lessons Learned",
    "Status Report",
    "Project Closure"
]

# Sections are dynamically generated by AI based on template type (unlimited)
# These are just examples for reference
EXAMPLE_SECTIONS = {
    "Project Charter": ["Objectives", "Scope", "Stakeholders", "Success Criteria", "Assumptions", "Constraints"],
    "Project Plan": ["Phases", "Milestones", "Deliverables", "Dependencies", "Resources", "Timeline"],
    "Risk Management": ["Risks", "Mitigation Strategies", "Contingency Plans", "Risk Owners", "Probability Assessment", "Impact Analysis"],
    "Quality Management": ["Quality Standards", "Quality Metrics", "Quality Control", "Quality Assurance", "Testing Procedures", "Acceptance Criteria"],
    "Resource Management": ["Team Roles", "Resource Allocation", "Skill Requirements", "Training Needs", "Resource Constraints", "Capacity Planning"],
    "Communication Plan": ["Stakeholder Communication", "Meeting Schedule", "Reporting Structure", "Communication Channels", "Escalation Procedures", "Documentation"],
    "Stakeholder Management": ["Stakeholder Identification", "Stakeholder Analysis", "Engagement Strategy", "Communication Needs", "Influence Assessment", "Stakeholder Register"],
    "Budget Management": ["Cost Estimates", "Budget Allocation", "Cost Control", "Financial Tracking", "Variance Analysis", "Funding Sources"],
    "Schedule Management": ["Timeline", "Critical Path", "Dependencies", "Milestones", "Resource Leveling", "Schedule Baseline"],
    "Scope Management": ["Scope Statement", "Deliverables", "Exclusions", "Acceptance Criteria", "Change Control", "Scope Verification"],
    "Procurement Management": ["Vendor Selection", "Contract Management", "Procurement Strategy", "Supplier Evaluation", "Purchase Orders", "Vendor Performance"],
    "Change Management": ["Change Requests", "Impact Assessment", "Approval Process", "Change Log", "Stakeholder Communication", "Implementation Plan"],
    "Issue Management": ["Issue Log", "Issue Resolution", "Escalation Procedures", "Issue Tracking", "Root Cause Analysis", "Preventive Actions"],
    "Lessons Learned": ["Successes", "Challenges", "Best Practices", "Recommendations", "Process Improvements", "Knowledge Transfer"],
    "Status Report": ["Progress Summary", "Accomplishments", "Upcoming Activities", "Issues and Risks", "Budget Status", "Schedule Status"],
    "Project Closure": ["Final Deliverables", "Acceptance Sign-off", "Resource Release", "Documentation Archive", "Post-Project Review", "Closure Report"]
}

# AI Generator Configuration
METHODOLOGIES = [
    "Agile",
    "Scrum",
    "Kanban",
    "Waterfall",
    "PRINCE2",
    "Lean",
    "Six Sigma",
    "Hybrid",
    "PMI PMBOK",
    "SAFe (Scaled Agile Framework)",
    "Extreme Programming (XP)",
    "Crystal",
    "Feature-Driven Development (FDD)",
    "Dynamic Systems Development Method (DSDM)",
    "Adaptive Project Framework (APF)",
    "Critical Path Method (CPM)",
    "Critical Chain Project Management (CCPM)",
    "PERT (Program Evaluation Review Technique)",
    "Lean Six Sigma",
    "Scrumban",
    "DevOps",
    "Disciplined Agile Delivery (DAD)",
    "Large-Scale Scrum (LeSS)",
    "Nexus Framework",
    "Spotify Model",
    "Shape Up",
    "Getting Things Done (GTD)",
    "Outcome-Driven Innovation (ODI)",
    "Benefits Realization Management",
    "Adaptive Project Management"
]

DOCUMENT_FORMATS = [
    "WORD",
    "EXCEL",
    "POWERPOINT"
]

def verify_openai_config():
    """Verify OpenAI API key is configured"""
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        print("⚠️  WARNING: OPENAI_API_KEY not set in environment")
        return False
    
    if len(api_key) < 20:
        print("⚠️  WARNING: OPENAI_API_KEY appears to be invalid (too short)")
        return False
    
    print(f"✅ OpenAI API key configured (length: {len(api_key)})")
    return True

def verify_database_connection():
    """Verify database connection and template data"""
    try:
        with app.app_context():
            template_count = Template.query.count()
            industries = db.session.query(Template.industry).distinct().count()
            categories = db.session.query(Template.category).distinct().count()
            
            print(f"✅ Database connected")
            print(f"   Templates: {template_count}")
            print(f"   Industries: {industries}")
            print(f"   Categories: {categories}")
            
            if template_count == 0:
                print("⚠️  WARNING: No templates in database")
                return False
            
            return True
            
    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        return False

def verify_ai_suggestor_data():
    """Verify AI Suggestor has all necessary data"""
    try:
        with app.app_context():
            # Get actual template categories from database
            db_categories = sorted(set(row[0] for row in db.session.query(Template.category).distinct().all()))
            
            print("\n📊 AI Suggestor Configuration:")
            print(f"   Template Types: ∞ UNLIMITED (AI supports ANY template type)")
            print(f"   Sections: ∞ UNLIMITED (dynamically generated by AI)")
            print(f"   Database Categories: {len(db_categories)} (for browsing existing templates)")
            print(f"   Example Template Types: {len(EXAMPLE_TEMPLATE_TYPES)} (reference only)")
            
            print("\n   How it works:")
            print("   • Users can request ANY project management template")
            print("   • AI generates suggestions for ANY template type")
            print("   • AI creates sections dynamically based on template type")
            print("   • No predefined limits or restrictions")
            
            print("\n   Sample Database Categories (for browsing):")
            for cat in db_categories[:5]:
                print(f"      - {cat}")
            if len(db_categories) > 5:
                print(f"      ... and {len(db_categories) - 5} more")
            
            print("\n✅ AI Suggestor: Supports ANY template type (∞ unlimited)")
            return True
            
    except Exception as e:
        print(f"❌ AI Suggestor verification failed: {e}")
        return False

def verify_ai_generator_data():
    """Verify AI Generator has all necessary data"""
    print("\n📊 AI Generator Configuration:")
    print(f"   Template Types: ∞ UNLIMITED (AI generates ANY document)")
    print(f"   Methodologies: {len(METHODOLOGIES)}")
    print(f"   Document Formats: {len(DOCUMENT_FORMATS)}")
    
    # List methodologies
    print("   Supported Methodologies:")
    for methodology in METHODOLOGIES:
        print(f"      - {methodology}")
    
    # List formats
    print("   Supported Formats:")
    for format_type in DOCUMENT_FORMATS:
        print(f"      - {format_type}")
    
    print("✅ AI Generator configuration complete")
    return True

def verify_template_categories():
    """Verify template categories are available in database"""
    try:
        with app.app_context():
            db_categories = sorted(set(row[0] for row in db.session.query(Template.category).distinct().all()))
            
            print("\n📊 AI Capability:")
            print(f"   Supported Template Types: ∞ UNLIMITED (ANY type user requests)")
            print(f"   Database Templates: {len(db_categories)} (pre-built for quick access)")
            print(f"   Example Config Types: {len(EXAMPLE_TEMPLATE_TYPES)} (reference only)")
            
            print("\n   ✅ AI can generate suggestions for ANY template type")
            print("   ✅ AI can create ANY project management document")
            print("   ✅ No restrictions on template types or sections")
            print(f"   ✅ Database has {len(db_categories)} pre-built templates for convenience")
            
            return True
            
    except Exception as e:
        print(f"❌ Category verification failed: {e}")
        return False

def seed_ai_components(mode='verify'):
    """
    Seed AI components configuration
    
    Modes:
    - 'verify': Only check without making changes
    - 'export': Export current configuration to JSON
    """
    
    print("=" * 80)
    print("AI COMPONENTS DATA SEEDING")
    print("=" * 80)
    print(f"Mode: {mode}")
    print()
    
    try:
        # Verify OpenAI configuration
        openai_ok = verify_openai_config()
        
        # Verify database connection
        db_ok = verify_database_connection()
        
        # Verify AI Suggestor data
        suggestor_ok = verify_ai_suggestor_data()
        
        # Verify AI Generator data
        generator_ok = verify_ai_generator_data()
        
        # Verify template category alignment
        alignment_ok = verify_template_categories()
        
        # Export configuration if requested
        if mode == 'export':
            import json
            # Get actual categories from database
            with app.app_context():
                db_categories = sorted(set(row[0] for row in db.session.query(Template.category).distinct().all()))
            
            config = {
                'note': 'AI supports UNLIMITED template types - can generate ANY project management document',
                'ai_capability': 'unlimited',
                'template_types': 'ANY (user can request any template type)',
                'sections': 'dynamically generated by AI based on template type',
                'database_categories': db_categories,
                'database_category_count': len(db_categories),
                'example_template_types': EXAMPLE_TEMPLATE_TYPES,
                'example_sections': EXAMPLE_SECTIONS,
                'methodologies': METHODOLOGIES,
                'document_formats': DOCUMENT_FORMATS
            }
            
            output_file = 'ai_components_config.json'
            with open(output_file, 'w') as f:
                json.dump(config, f, indent=2)
            
            print(f"\n✅ Configuration exported to {output_file}")
        
        # Print summary
        print()
        print("=" * 80)
        print("SUMMARY")
        print("=" * 80)
        print(f"OpenAI API: {'✅ OK' if openai_ok else '❌ FAIL'}")
        print(f"Database: {'✅ OK' if db_ok else '❌ FAIL'}")
        print(f"AI Suggestor: {'✅ OK' if suggestor_ok else '❌ FAIL'}")
        print(f"AI Generator: {'✅ OK' if generator_ok else '❌ FAIL'}")
        print(f"Category Alignment: {'✅ OK' if alignment_ok else '❌ FAIL'}")
        print("=" * 80)
        
        all_ok = openai_ok and db_ok and suggestor_ok and generator_ok and alignment_ok
        
        if all_ok:
            print("\n🎉 All AI components configured correctly!")
        else:
            print("\n⚠️  Some components need attention")
        
        return all_ok
        
    except Exception as e:
        print(f"❌ CRITICAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Seed AI components configuration')
    parser.add_argument('--mode', choices=['verify', 'export'], 
                       default='verify', help='Operation mode')
    
    args = parser.parse_args()
    
    success = seed_ai_components(mode=args.mode)
    sys.exit(0 if success else 1)

